'use client';
import {useEffect,useState,useRef, type ReactNode} from 'react';
import {Box,Calculator,LayoutDashboard,ClipboardList,Printer,Package,Users,Wallet,Settings,Plus,ArrowUpRight,Clock,Check,Download,RefreshCw,ChevronRight,Layers,Trash2,Camera,FileText,LogOut,Paperclip,PiggyBank} from 'lucide-react';
import {SidebarProvider,Sidebar,SidebarHeader,SidebarContent,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarInset,SidebarTrigger,useSidebar} from '@/components/ui/sidebar';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Switch} from '@/components/ui/switch';
import {Checkbox} from '@/components/ui/checkbox';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Table,TableHeader,TableHead,TableRow,TableBody,TableCell} from '@/components/ui/table';
import {Empty,EmptyHeader,EmptyTitle,EmptyDescription} from '@/components/ui/empty';
import {Skeleton} from '@/components/ui/skeleton';
import {Toaster} from '@/components/ui/sonner';
import {toast} from 'sonner';
import {safeSupplierLink,emptyState,stock,received,money,stages,type State,type Calculation,type Kind,type Entity,type Quote,type Order} from '@/lib/domain';
import {Precificacao} from './precificacao';
import {Investimentos} from './investimentos';
import {situacaoVencimento} from '@/lib/financeiro';
const brl=(v:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v);
const today=()=>new Date().toLocaleDateString('en-CA',{timeZone:'America/Sao_Paulo'});
const dt=(v:string)=>v?new Date(v+'T12:00:00').toLocaleDateString('pt-BR'):'—';
const htmlEscape=(v:unknown)=>String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]||ch));
const nav=[['Visão geral',LayoutDashboard],['Precificação',Calculator],['Orçamentos',FileText],['Pedidos',ClipboardList],['Produção',Printer],['Materiais',Package],['Cadastros',Users],['Financeiro',Wallet],['Investimentos',PiggyBank],['Configurações',Settings]] as const;
function Field({label,children,hint}:{label:string;children:ReactNode;hint?:string}){return <label className="field"><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>}
function Input({label,value,onChange,type='text',hint,min,max,step,required=false}:{label:string;value:any;onChange:(v:any)=>void;type?:string;hint?:string;min?:number;max?:number;step?:string;required?:boolean}){if(type==='payment')return <Field label={label} hint={hint}><select required={required} className="select-trigger" value={value||'avista'} onChange={e=>onChange(e.target.value)}><option value="avista">À vista</option><option value="parcelado">Parcelado</option></select></Field>;return <Field label={label} hint={hint}><input required={required} type={type} value={value??(label.includes('parcelas')?1:'')} min={min} max={max} step={step??(type==='number'?'any':undefined)} onChange={e=>onChange(type==='number'?(e.target.value===''?'':Number(e.target.value)):e.target.value)}/></Field>}
const parseBrl=(v:string)=>{const normalized=v.replace(/[^0-9,.-]/g,'').replace(/\./g,'').replace(',','.');const n=Number(normalized);return Number.isFinite(n)?n:0};
function MoneyInput({label,value,onChange,hint,min=0,required=false}:{label:string;value:any;onChange:(v:number)=>void;hint?:string;min?:number;required?:boolean}){const [editing,setEditing]=useState(false),[text,setText]=useState(brl(Number(value)||0));useEffect(()=>{if(!editing)setText(brl(Number(value)||0))},[value,editing]);return <Field label={label} hint={hint}><input required={required} inputMode="decimal" value={text} min={min} onFocus={()=>{setEditing(true);setText((Number(value)||0).toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2}))}} onChange={e=>{setText(e.target.value);onChange(parseBrl(e.target.value))}} onBlur={()=>{const n=parseBrl(text);onChange(n);setText(brl(n));setEditing(false)}}/></Field>}
function Pick({label,value,onChange,options,hint}:{label:string;value:string;onChange:(v:string)=>void;options:{id:string;name?:string;[key:string]:any}[];hint?:string}){return <Field label={label} hint={hint}><Select value={value||'_none'} onValueChange={v=>onChange(v==='_none'?'':v)}><SelectTrigger className="select-trigger"><SelectValue placeholder="Selecione"/></SelectTrigger><SelectContent><SelectItem value="_none">Selecione</SelectItem>{options.map(x=><SelectItem key={x.id} value={x.id}>{x.name}</SelectItem>)}</SelectContent></Select></Field>}
function Blank({title,text,action}:{title:string;text:string;action?:ReactNode}){return <Empty className="empty"><EmptyHeader><div className="empty-icon"><Layers size={24}/></div><EmptyTitle>{title}</EmptyTitle><EmptyDescription>{text}</EmptyDescription></EmptyHeader>{action}</Empty>}
function Badge({children,tone='blue'}:{children:ReactNode;tone?:string}){return <span className={'badge '+tone}>{children}</span>}
function Navigation({page,setPage}:{page:string;setPage:(p:string)=>void}){const {setOpenMobile}=useSidebar();return <Sidebar><SidebarHeader className="brand"><div className="brand-mark"><Box size={27}/></div><div><strong>GESTÃO<span>3D</span></strong><small>DA IDEIA À ENTREGA</small></div></SidebarHeader><SidebarContent><div className="nav-label">ESPAÇO DE TRABALHO</div><SidebarMenu className="navigation">{nav.map(([n,I])=><SidebarMenuItem key={n}><SidebarMenuButton isActive={page===n} onClick={()=>{setPage(n);setOpenMobile(false)}}><I/><span>{n}</span>{page===n&&<ChevronRight className="ml-auto"/>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarContent><SidebarFooter className="side-footer"><div className="avatar">F</div><div><b>Fabricando 3D</b><small>Gestão de impressão 3D</small></div></SidebarFooter></Sidebar>}
const entityLabels:Record<Kind,string>={customers:'Clientes',suppliers:'Fornecedores',materials:'Materiais',printers:'Impressoras',products:'Produtos'};
const entityFields:Record<Kind,[string,string,string][]>={customers:[['name','Nome / razão social','text'],['phone','Telefone / WhatsApp','text'],['email','E-mail','email'],['notes','Observações','text']],suppliers:[['name','Nome do fornecedor','text'],['phone','Telefone','text'],['notes','Observações','text']],materials:[['name','Nome do material','text'],['brand','Marca','text'],['model','Modelo','text'],['type','Tipo (PLA, PETG, ABS…)','text'],['color','Cor','text'],['kgPrice','Preço por kg (R$)','number'],['spoolCount','Quantidade de bobinas','number'],['spoolWeight','Peso líquido por bobina (g)','number'],['spoolPrice','Preço por bobina (R$)','number'],['supplierId','Fornecedor da bobina','supplier'],['paymentType','Forma de pagamento','payment'],['installments','Quantidade de parcelas','number'],['minimum','Estoque mínimo (g)','number'],['notes','Observações','text']],printers:[['name','Nome da impressora','text'],['model','Modelo','text'],['brand','Marca','text'],['power','Potência média (W)','number'],['value','Valor pago na impressora (R$)','number'],['lifeHours','Vida útil (horas)','number'],['machineRate','Hora de máquina (R$/h), deixe 0 para calcular pelo valor ÷ vida útil','number'],['notes','Observações','text']],products:[['name','Nome do produto','text'],['category','Categoria','text'],['model','Modelo','text'],['color','Cor','text'],['description','Descrição','text'],['weight','Peso por peça (g)','number'],['hours','Tempo por peça (h)','number']]};
export default function Manager({usuario,aoSair}:{usuario:{name:string;email:string;role:string};aoSair:()=>void}){
 const [page,setPage]=useState('Visão geral'),[s,setS]=useState<State>(emptyState()),[revision,setRevision]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false),[dialog,setDialog]=useState<any>(null),[form,setForm]=useState<any>({}),[search,setSearch]=useState(''),[month,setMonth]=useState('');
 const current=useRef({s,revision});current.current={s,revision};const saving=useRef(false);
 async function load(){setLoading(true);setError('');try{const r=await fetch('/api/workspace',{cache:'no-store'});if(r.status===401||r.status===403){aoSair();return}const v:any=await r.json();if(!r.ok)throw Error(v.error);setS(v.state);setRevision(v.revision);return v.state as State}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{setMonth(today().slice(0,7));load()},[]);
 async function mutate(action:any){if(saving.current)return false;saving.current=true;setBusy(true);try{const r=await fetch('/api/workspace',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:current.current.revision,action})}),v:any=await r.json();if(!r.ok)throw Error(v.error);current.current={s:v.state,revision:v.revision};setS(v.state);setRevision(v.revision);toast.success('Salvo com sucesso');return true}catch(e:any){toast.error(e.message);return false}finally{saving.current=false;setBusy(false)}}
 const patch=(k:string,v:any)=>setForm((f:any)=>({...f,[k]:v}));
 function openEntity(kind:Kind,entity?:Entity){const materialDefaults=entity?{spoolCount:0,spoolWeight:0,spoolPrice:0,supplierId:''}:{spoolCount:1,spoolWeight:1000,spoolPrice:0,supplierId:''};setForm(kind==='suppliers'?{supplierType:entity?'':'online',platform:'',link:'',address:'',name:'',phone:'',notes:'',...entity}:kind==='materials'?{...materialDefaults,...entity}:entity?{...entity}:Object.fromEntries(entityFields[kind].map(([k,,t])=>[k,t==='number'?0:''])));setDialog({type:'entity',kind,id:entity?.id,title:entity?(kind==='materials'?'Editar bobina / material':'Editar cadastro'):(kind==='materials'?'Nova bobina de filamento':'Novo cadastro · '+entityLabels[kind])})}
 function openOrder(o:Order){setForm({...o});setDialog({type:'production',id:o.id,title:'Pedido #'+String(o.number).padStart(3,'0')+' · '+o.customerName})}
 function editCompany(){setForm({company:s.settings.company||'Gestão 3D',document:s.settings.document||'',phone:s.settings.phone||'',email:s.settings.email||'',address:s.settings.address||'',logo:s.settings.logo||''});setDialog({type:'company',title:'Dados da empresa'})}
 function payment(o:Order){setForm({orderId:o.id,amount:money(o.revenue-received(s,o.id)),date:today(),method:'Pix'});setDialog({type:'payment',title:'Registrar recebimento'})}
 function purchase(){setForm({description:'',supplierId:'',materialId:'',grams:1000,amount:0,date:today(),due:today(),paid:false,category:'Materiais',paymentType:'avista',installments:1});setDialog({type:'purchase',title:'Nova compra / despesa'})}
 async function saveDialog(e:React.FormEvent){e.preventDefault();let a:any={type:dialog.type,data:form,id:dialog.id};if(dialog.type==='entity'){a.kind=dialog.kind;if(dialog.kind==='suppliers'&&!form.supplierType){toast.error('Selecione Online ou Físico.');return}}if(dialog.type==='production')a.data={printed:form.printed,painted:form.painted,packed:form.packed,delivered:form.delivered,stage:form.stage};if(await mutate(a))setDialog(null)}
 async function upload(file:File){const f=new FormData();f.append('file',file);const r=await fetch('/api/files',{method:'POST',body:f}),v:any=await r.json();if(!r.ok)throw Error(v.error);return v as {url:string;nome:string};}
 function exportData(){const blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),...current.current},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='gestao3d-'+today()+'.json';a.click();URL.revokeObjectURL(url)}
 function printDocument(title:string,content:string){
  const cfg=current.current.s.settings,popup=window.open('','_blank');
  if(!popup){toast.error('O navegador bloqueou a janela de impressão. Permita janelas para este sistema e tente novamente.');return}
  const logo=cfg.logo?'<img class="print-logo" src="'+htmlEscape(cfg.logo)+'" alt="Logo da empresa"/>':'';
  const details=[cfg.document&&'CPF/CNPJ: '+htmlEscape(cfg.document),cfg.phone&&'Telefone: '+htmlEscape(cfg.phone),cfg.email&&htmlEscape(cfg.email),cfg.address&&htmlEscape(cfg.address).replace(/\r?\n/g,'<br>')].filter(Boolean).map(v=>'<span>'+v+'</span>').join('');
  popup.document.open();
  popup.document.write('<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+htmlEscape(title)+'</title><style>@page{size:A4;margin:16mm}*{box-sizing:border-box}body{font:14px Arial,Helvetica,sans-serif;color:#20394c;margin:0}.sheet{max-width:800px;margin:0 auto}.toolbar{display:flex;justify-content:flex-end;margin:0 0 18px}.toolbar button{background:#007e8e;color:white;border:0;border-radius:6px;padding:11px 16px;font-size:14px;cursor:pointer}.print-header{display:flex;gap:20px;align-items:center;border-bottom:2px solid #087e8f;padding-bottom:17px;margin-bottom:26px}.print-logo{max-width:86px;max-height:70px;object-fit:contain}.seller{flex:1}.seller h2{font-size:19px;margin:0 0 7px;color:#173249}.seller span{display:block;font-size:11px;line-height:1.55;color:#60778a}.doc-heading{display:flex;justify-content:space-between;align-items:flex-start;gap:16px;margin-bottom:22px}.doc-heading h1{font-size:25px;letter-spacing:.3px;margin:0;color:#173249}.doc-number{font-size:13px;color:#597489;text-align:right}.section{border:1px solid #dce5eb;border-radius:7px;padding:14px 16px;margin:14px 0}.section h3{font-size:11px;letter-spacing:.7px;text-transform:uppercase;color:#6c8496;margin:0 0 8px}.section p{font-size:13px;line-height:1.6;margin:3px 0}.muted{color:#6c8496}table{width:100%;border-collapse:collapse;margin:17px 0}th{text-align:left;background:#eff5f8;color:#526e81;font-size:10px;text-transform:uppercase;letter-spacing:.5px}th,td{padding:11px 10px;border-bottom:1px solid #e5ebef;vertical-align:top}td{font-size:12px}th:last-child,td:last-child{text-align:right}th:nth-child(2),td:nth-child(2){text-align:center}.small{display:block;color:#758a99;font-size:11px;margin-top:3px}.totals{display:flex;justify-content:flex-end;margin:18px 0 30px}.total-box{min-width:245px;border-top:2px solid #087e8f;padding-top:12px;display:flex;justify-content:space-between;gap:25px;font-size:15px;font-weight:bold}.receipt-copy{font-size:16px;line-height:1.8;margin:27px 0}.receipt-copy strong{font-size:18px}.signature-row{display:flex;gap:38px;margin-top:76px}.signature{flex:1;text-align:center;border-top:1px solid #8396a3;padding-top:8px;color:#617889;font-size:11px}.footnote{font-size:11px;color:#718797;line-height:1.5;margin-top:25px}@media print{.toolbar{display:none}.sheet{max-width:none}}@media(max-width:600px){.sheet{padding:12px}.doc-heading{flex-direction:column}.doc-number{text-align:left}.print-header{align-items:flex-start}}</style></head><body><main class="sheet"><div class="toolbar"><button onclick="window.print()">Imprimir / Salvar como PDF</button></div><header class="print-header">'+logo+'<div class="seller"><h2>'+htmlEscape(cfg.company||'Minha empresa')+'</h2>'+details+'</div></header>'+content+'</main></body></html>');
  popup.document.close();popup.focus();window.setTimeout(()=>popup.print(),350);
 }
 function printQuote(q:Quote){
  const data=current.current.s,customerData=data.customers.find(x=>x.id===q.customerId),number=String(q.number).padStart(3,'0'),contact=[customerData?.phone&&'Telefone: '+htmlEscape(customerData.phone),customerData?.email&&htmlEscape(customerData.email)].filter(Boolean).join(' · ');
  const rows=q.items.map(i=>'<tr><td><b>'+htmlEscape(i.name)+'</b><span class="small">'+htmlEscape(i.category||'Peça personalizada')+'</span></td><td>'+Number(i.calculation.quantity).toLocaleString('pt-BR')+'</td><td>'+brl(Number(i.calculation.quantity)>0?i.revenue/Number(i.calculation.quantity):0)+'</td><td>'+brl(i.revenue)+'</td></tr>').join('');
  const notes=q.notes?'<section class="section"><h3>Observações</h3><p>'+htmlEscape(q.notes).replace(/\r?\n/g,'<br>')+'</p></section>':'';
  const content='<div class="doc-heading"><h1>ORÇAMENTO</h1><div class="doc-number">Nº '+number+'<br>Emitido em '+dt(q.date)+'<br>Válido até '+dt(q.due)+'</div></div><section class="section"><h3>Cliente</h3><p><b>'+htmlEscape(q.customerName)+'</b></p>'+(contact?'<p class="muted">'+contact+'</p>':'')+'</section><table><thead><tr><th>Produto / serviço</th><th>Qtd.</th><th>Valor unitário</th><th>Subtotal</th></tr></thead><tbody>'+rows+'</tbody></table><div class="totals"><div class="total-box"><span>Valor total</span><span>'+brl(q.revenue)+'</span></div></div>'+notes+'<p class="footnote">Este documento apresenta os valores e o prazo registrados no orçamento. A produção começa após a aprovação.</p><div class="signature-row"><div class="signature">Aceite do cliente</div><div class="signature">Responsável pela empresa</div></div>';
  printDocument('Orçamento nº '+number,content);
 }
 function printReceipt(paymentRecord:any){
  const data=current.current.s,order=data.orders.find(o=>o.id===paymentRecord.orderId),number=order?String(order.number).padStart(3,'0'):'—',receiptNumber='REC-'+String(paymentRecord.id||'').replace(/-/g,'').slice(0,8).toUpperCase(),customerName=order?.customerName||'Cliente',paidToDate=order?received(data,order.id):money(Number(paymentRecord.amount)||0),balance=order?Math.max(0,money(order.revenue-paidToDate)):0,items=order?.items.map(i=>i.name).join(', ')||'Pedido de impressão 3D';
  const content='<div class="doc-heading"><h1>RECIBO</h1><div class="doc-number">'+receiptNumber+'<br>Data: '+dt(paymentRecord.date)+'</div></div><p class="receipt-copy">Recebi de <strong>'+htmlEscape(customerName)+'</strong> a importância de <strong>'+brl(paymentRecord.amount)+'</strong>, referente ao pagamento do pedido #'+number+'.</p><section class="section"><h3>Detalhes do recebimento</h3><p><b>Forma de pagamento:</b> '+htmlEscape(paymentRecord.method)+'</p><p><b>Referente a:</b> '+htmlEscape(items)+'</p>'+(order?'<p><b>Valor total do pedido:</b> '+brl(order.revenue)+'</p><p><b>Total recebido até agora:</b> '+brl(paidToDate)+'</p><p><b>Saldo do pedido:</b> '+brl(balance)+'</p>':'')+'</section><p class="footnote">Recibo emitido para confirmar o recebimento do valor informado nesta data.</p><div class="signature-row"><div class="signature">Assinatura / carimbo</div></div>';
  printDocument('Recibo '+receiptNumber,content);
 }
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();Promise.resolve(context.registerTool({name:'navigate_gestao3d',description:'Abre um módulo da Gestão 3D sem alterar registros.',inputSchema:{type:'object',properties:{module:{type:'string',enum:nav.map(x=>x[0])}},required:['module'],additionalProperties:false},annotations:{readOnlyHint:true},execute:async(input:any)=>{if(!nav.some(x=>x[0]===input.module))throw Error('Módulo inválido');setPage(input.module);return {module:input.module}}},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort()},[]);
 const orders=s.orders.filter(o=>(o.customerName+' '+o.number+' '+o.items.map(i=>i.name).join(' ')).toLowerCase().includes(search.toLowerCase()));
 const periodOrders=s.orders.filter(o=>o.date.startsWith(month));const revenue=periodOrders.reduce((a,b)=>a+b.revenue,0),profit=periodOrders.reduce((a,b)=>a+b.revenue-b.cost,0),inflow=s.payments.filter(p=>p.date.startsWith(month)).reduce((a,b)=>a+b.amount,0),outflow=s.purchases.filter(p=>p.paid&&p.paidDate.startsWith(month)).reduce((a,b)=>a+b.amount,0),pending=s.orders.reduce((a,b)=>a+b.revenue-received(s,b.id),0);
 const active=s.orders.filter(o=>!o.delivered),low=s.materials.filter(m=>stock(s,m.id)<=m.minimum);
 function table(headers:string[],rows:ReactNode[][]){return rows.length?<Table><TableHeader><TableRow>{headers.map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map((row,i)=><TableRow key={i}>{row.map((v,j)=><TableCell key={j}>{v}</TableCell>)}</TableRow>)}</TableBody></Table>:<Blank title="Nenhum registro ainda" text="Os registros aparecerão aqui assim que você começar."/>}
 function entities(kind:Kind){const list=s[kind];return <><div className="section-heading"><div><h2>{entityLabels[kind]}</h2><p>{list.length} cadastros</p></div><button className="btn" onClick={()=>openEntity(kind)}><Plus size={17}/> Novo cadastro</button></div><div className="panel">{table(['Nome','Detalhes',''],list.map(x=>[<span className="record-name">{x.photo&&<img className="mini-photo" src={x.photo} alt=""/>}{x.name}</span>,kind==='materials'?`${x.brand?x.brand+' · ':''}${x.type} · ${x.color} · ${brl(x.kgPrice)}/kg`:kind==='printers'?[x.model,x.brand,`${brl(x.machineRate)}/h · ${x.power} kW`].filter(Boolean).join(' · '):kind==='products'?[x.category,x.model,x.color,`${x.weight} g`,`${x.hours} h`].filter(Boolean).join(' · '):kind==='suppliers'?<>{x.supplierType==='online'?<><Badge>Online</Badge><span className="block muted">{x.platform||'Plataforma não informada'}</span></>:x.supplierType==='fisico'?<><Badge>Físico</Badge><span className="block muted">{x.address||'Endereço não informado'}{x.phone?' · '+x.phone:''}</span></>:<span>{x.phone||'Tipo não informado'}</span>}</>:x.phone||'—',<div className="row-actions">{kind==='suppliers'&&x.supplierType==='online'&&safeSupplierLink(x.link)&&<a className="text-btn" href={safeSupplierLink(x.link)} target="_blank" rel="noopener noreferrer">Abrir loja <ArrowUpRight size={15}/></a>}<button className="text-btn" onClick={()=>openEntity(kind,x)}>Editar</button></div>]))}</div></>}
 return <SidebarProvider><Navigation page={page} setPage={p=>{setPage(p);setSearch('')}}/><SidebarInset className="main-shell"><header className="topbar"><div className="flex items-center gap-3"><SidebarTrigger aria-label="Abrir ou recolher menu"/><span className="breadcrumb">Minha empresa <ChevronRight size={14}/> <b>{page}</b></span></div><div className="top-actions"><button aria-label="Atualizar dados" title="Atualizar dados" onClick={()=>load()}><RefreshCw size={17}/></button><span className="private-label" title={usuario.email}>{usuario.name}</span><button className="text-btn" onClick={async()=>{try{await fetch('/api/auth/logout',{method:'POST',headers:{'Content-Type':'application/json'}})}catch{}aoSair()}}><LogOut size={16}/> Sair</button><div className="avatar light" aria-hidden="true">{(usuario.name.trim()[0]||'?').toUpperCase()}</div></div></header><main className="workspace"><div className="page-heading"><div><p className="eyebrow">OPERAÇÃO / IMPRESSÃO 3D</p><h1>{page}</h1><p>{page==='Precificação'?'Cada custo no lugar. Cada peça com o preço certo.':page==='Visão geral'?'Sua operação, do orçamento à entrega.':page==='Produção'?'Organize a fila e acompanhe cada etapa.':page==='Materiais'?'Filamentos, compras e consumo em um só lugar.':page==='Financeiro'?'Recebimentos e pagamentos separados da produção.':page==='Investimentos'?'O que já foi investido na empresa e quanto já voltou.':page==='Configurações'?'Dados da empresa para orçamentos, recibos e custos padrão.':'Informações conectadas, sem retrabalho.'}</p></div>{['Pedidos','Orçamentos','Visão geral'].includes(page)&&<button className="btn" onClick={()=>setPage('Precificação')}><Plus size={18}/> Novo orçamento</button>}</div>
 {error&&<div className="error" role="alert">{error} <button onClick={()=>load()}>Tentar novamente</button></div>}
 {loading?<div className="loading-grid">{[1,2,3].map(x=><Skeleton key={x} className="h-32 w-full rounded-xl"/>)}</div>:<>
 {page==='Precificação'&&<Precificacao s={s} ocupado={busy||!!error} salvar={mutate} enviarArquivo={upload} abrirCadastro={k=>openEntity(k)} irPara={setPage}/>}
 {page==='Visão geral'&&<><div className="period"><Input label="Período" type="month" value={month} onChange={setMonth}/><Badge>{periodOrders.length} pedidos no mês</Badge></div><div className="metrics">{[['Vendas do mês',revenue,'Pedidos aprovados'],['Resultado estimado',profit,'Vendas menos custos orçados'],['Recebido no mês',inflow,'Por data de recebimento'],['A receber · geral',pending,'Já desconta os pagamentos']].map(([t,v,h])=><div className="metric" key={t}><span>{t}</span><strong>{brl(Number(v))}</strong><small>{h}</small></div>)}</div><div className="overview-grid"><div className="panel"><div className="panel-heading"><h2>Ritmo da produção</h2><Badge>{active.length} em aberto</Badge></div><div className="stage-bars">{stages.map((stage,i)=>{const n=s.orders.filter(o=>o.stage===stage).length;return <div key={stage}><span>{stage}</span><div className="bar-track"><div style={{width:s.orders.length?`${n/s.orders.length*100}%`:'0%',background:i===5?'#4f9b8b':'#078b9f'}}/></div><b>{n}</b></div>})}</div></div><div className="panel"><div className="panel-heading"><h2>Atenção hoje</h2></div><div className="attention"><div><Clock/><span>Pedidos atrasados</span><b>{active.filter(o=>o.due<today()).length}</b></div><div><Package/><span>Materiais no mínimo</span><b>{low.length}</b></div><div><Wallet/><span>Contas vencidas</span><b>{s.purchases.filter(p=>!p.paid&&p.due<today()).length}</b></div></div><div className="cash-note"><span>Saldo de movimentações no mês</span><b>{brl(inflow-outflow)}</b><small>Recebimentos menos pagamentos. Não é lucro.</small></div></div></div><div className="panel"><div className="panel-heading"><h2>Próximas entregas</h2><button className="text-btn" onClick={()=>setPage('Pedidos')}>Ver pedidos <ArrowUpRight size={16}/></button></div>{active.length?table(['Pedido','Cliente','Entrega','Etapa'],[...active].sort((a,b)=>a.due.localeCompare(b.due)).slice(0,5).map(o=>[<button className="text-btn" onClick={()=>openOrder(o)}>#{o.number}</button>,o.customerName,<span className={o.due<today()?'negative':''}>{dt(o.due)}</span>,<Badge>{o.stage}</Badge>])):<Blank title="Sua próxima impressão começa aqui" text="Cadastre seus materiais e crie o primeiro orçamento. Ao aprová-lo, o pedido entra na fila de produção." action={<button className="btn" onClick={()=>setPage('Precificação')}>Criar orçamento</button>}/>}</div></>}
 {page==='Orçamentos'&&<div className="panel">{table(['Orçamento / data','Cliente e itens','Valor','Situação',''],s.quotes.slice().reverse().map(q=>[<><b>#{String(q.number).padStart(3,'0')}</b><small className="block muted">{dt(q.date)}</small></>,<>{q.customerName}<small className="block muted">{q.items.map(i=>i.name).join(', ')}</small></>,brl(q.revenue),<Badge tone={q.status==='Aprovado'?'green':'blue'}>{q.status}</Badge>,<div className="row-actions"><button className="text-btn" onClick={()=>{setForm(q);setDialog({type:'quoteDetail',title:'Orçamento #'+q.number})}}>Detalhes</button><button className="text-btn" onClick={()=>printQuote(q)}><Printer size={15}/> Imprimir orçamento</button>{q.status==='Aberto'&&<button className="btn small" disabled={busy} onClick={()=>mutate({type:'approve',id:q.id})}>Aprovar e gerar pedido</button>}</div>]))}</div>}
 {page==='Pedidos'&&<><div className="toolbar"><input aria-label="Buscar pedido" placeholder="Buscar cliente, peça ou número…" value={search} onChange={e=>setSearch(e.target.value)}/><Badge>{orders.length} pedidos</Badge></div><div className="panel">{table(['Pedido / cliente','Prazo','Produção','Total','Recebido / saldo',''],orders.slice().reverse().map(o=>[<><b>#{String(o.number).padStart(3,'0')} · {o.customerName}</b><small className="block muted">{o.items.map(i=>i.name).join(', ')}</small></>,<span className={!o.delivered&&o.due<today()?'negative':''}>{dt(o.due)}</span>,<Badge tone={o.delivered?'green':'blue'}>{o.stage}</Badge>,brl(o.revenue),<>{brl(received(s,o.id))}<small className="block muted">Falta {brl(o.revenue-received(s,o.id))}</small></>,<div className="row-actions"><button className="text-btn" onClick={()=>openOrder(o)}>Abrir</button>{received(s,o.id)<o.revenue&&<button className="btn small secondary" onClick={()=>payment(o)}>Receber</button>}</div>]))}</div></>}
 {page==='Produção'&&<><div className="production-summary"><Badge>{active.length} pedidos ativos</Badge><span>Ao registrar a impressão, o consumo previsto é baixado do estoque uma única vez.</span></div>{!s.orders.length?<div className="panel"><Blank title="Fila de produção vazia" text="Aprove um orçamento para gerar o primeiro pedido e iniciar a produção." action={<button className="btn" onClick={()=>setPage('Orçamentos')}>Ver orçamentos</button>}/></div>:<div className="kanban">{stages.map((stage,index)=><section key={stage} className="kanban-column"><h2><span className="stage-index">{index+1}</span>{stage}<b>{s.orders.filter(o=>o.stage===stage).length}</b></h2>{s.orders.filter(o=>o.stage===stage).map(o=><button className="job-card" key={o.id} onClick={()=>openOrder(o)}><span className="job-id">PEDIDO #{String(o.number).padStart(3,'0')}</span><strong>{o.items.map(i=>i.name).join(' + ')}</strong><p>{o.customerName}</p><div className="job-meta"><Clock size={14}/>{o.items.reduce((a,i)=>a+i.calculation.hours*i.calculation.quantity,0).toFixed(1)} h <span>{o.items.reduce((a,i)=>a+i.calculation.quantity,0)} peça(s)</span></div><div className={'job-due '+(!o.delivered&&o.due<today()?'negative':'')}>Entrega {dt(o.due)}<ArrowUpRight size={15}/></div></button>)}{!s.orders.some(o=>o.stage===stage)&&<p className="no-jobs">Nenhum pedido</p>}</section>)}</div>}</>}
 {page==='Materiais'&&<Tabs defaultValue="stock"><TabsList><TabsTrigger value="stock">Estoque</TabsTrigger><TabsTrigger value="purchases">Compras</TabsTrigger><TabsTrigger value="history">Movimentações</TabsTrigger></TabsList><TabsContent value="stock"><div className="section-heading"><h2>Bobinas de filamento</h2><div className="row-actions"><button className="btn secondary" onClick={()=>{setForm({materialId:'',grams:0,date:today(),reason:''});setDialog({type:'movement',title:'Entrada, perda ou ajuste de estoque'})}}>Ajustar estoque</button><button className="btn" onClick={()=>openEntity('materials')}><Plus size={17}/> Cadastrar bobina</button></div></div><div className="material-grid">{s.materials.map(m=><div className="material-card" key={m.id}><div className="flex justify-between"><div className="material-icon"><Layers size={26}/></div><Badge tone={stock(s,m.id)<=m.minimum?'orange':'green'}>{stock(s,m.id)<=m.minimum?'Estoque baixo':'Disponível'}</Badge></div><h2>{m.name}</h2><p>{[m.brand,m.model,m.type,m.color].filter(Boolean).join(' · ')}</p><div className="spool-meta">{m.spoolCount>0?<><span>{m.spoolCount} bobina(s)</span><span>{Number(m.spoolWeight||0).toLocaleString('pt-BR')} g cada</span></>:<span>Dados da bobina não informados</span>}{m.supplierId&&<span>{s.suppliers.find(x=>x.id===m.supplierId)?.name||'Fornecedor'}</span>}</div><strong>{stock(s,m.id).toLocaleString('pt-BR',{maximumFractionDigits:1})} <span>g</span></strong><div className="material-bottom"><span>{brl(m.kgPrice)}/kg</span><button className="text-btn" onClick={()=>openEntity('materials',m)}>Editar bobina</button></div><small>{m.spoolPrice>0?<>Preço da bobina: {brl(m.spoolPrice)} · </>:''}Mínimo: {m.minimum} g</small></div>)}</div>{!s.materials.length&&<div className="panel"><Blank title="Cadastre sua primeira bobina" text="Informe marca, modelo, tipo, cor, peso e valor da bobina. A quantidade cadastrada entra automaticamente no estoque inicial."/></div>}</TabsContent><TabsContent value="purchases"><div className="section-heading"><h2>Compras e despesas</h2><button className="btn" onClick={purchase}><Plus size={16}/> Nova compra</button></div><div className="panel">{table(['Data','Descrição','Total','Pagamento'],s.purchases.slice().reverse().map(p=>[dt(p.date),p.description,brl(p.amount),<div><Badge tone={p.paid?'green':'orange'}>{p.paid?'Pago':'A pagar'}</Badge><small className="block muted">{p.paymentType==='parcelado'?`Parcelado · ${p.installments}x`:'À vista'}</small></div>]))}</div></TabsContent><TabsContent value="history"><div className="panel">{table(['Data','Material','Quantidade','Motivo'],s.movements.slice().reverse().map(m=>[dt(m.date),s.materials.find(x=>x.id===m.materialId)?.name,<span className={m.grams<0?'negative':'positive'}>{m.grams>0?'+':''}{Number(m.grams.toFixed(2))} g</span>,m.reason]))}</div></TabsContent></Tabs>}
 {page==='Cadastros'&&<Tabs defaultValue="customers"><TabsList className="wrap-tabs">{(['customers','products','printers','suppliers'] as Kind[]).map(k=><TabsTrigger key={k} value={k}>{entityLabels[k]}</TabsTrigger>)}</TabsList>{(['customers','products','printers','suppliers'] as Kind[]).map(k=><TabsContent key={k} value={k}>{entities(k)}</TabsContent>)}</Tabs>}
 {page==='Financeiro'&&<><div className="period"><Input label="Período de caixa" type="month" value={month} onChange={setMonth}/></div><div className="metrics"><div className="metric"><span>Recebimentos no mês</span><strong>{brl(inflow)}</strong></div><div className="metric"><span>Pagamentos no mês</span><strong>{brl(outflow)}</strong></div><div className="metric"><span>Movimentação líquida</span><strong>{brl(inflow-outflow)}</strong></div><div className="metric"><span>A receber · geral</span><strong>{brl(pending)}</strong></div>{(()=>{const atrasadas=s.purchases.filter(p=>!p.paid&&situacaoVencimento(p.due,today()).tom==='atrasada');return <div className={'metric'+(atrasadas.length?' metric-alerta':'')}><span>Contas atrasadas</span><strong>{brl(atrasadas.reduce((a,b)=>a+(Number(b.amount)||0),0))}</strong><small>{atrasadas.length?atrasadas.length+' conta(s) passaram do vencimento':'Nenhuma conta atrasada'}</small></div>})()}</div><Tabs defaultValue="receive"><TabsList><TabsTrigger value="receive">A receber</TabsTrigger><TabsTrigger value="pay">A pagar</TabsTrigger><TabsTrigger value="history">Recebimentos</TabsTrigger></TabsList><TabsContent value="receive"><div className="panel">{table(['Pedido / cliente','Total','Recebido','Saldo',''],s.orders.filter(o=>o.revenue>received(s,o.id)).map(o=>['#'+o.number+' · '+o.customerName,brl(o.revenue),brl(received(s,o.id)),brl(o.revenue-received(s,o.id)),<button className="btn small" onClick={()=>payment(o)}>Registrar recebimento</button>]))}</div></TabsContent><TabsContent value="pay"><div className="section-heading"><h2>Contas a pagar · geral</h2><button className="btn" onClick={purchase}><Plus size={16}/> Nova despesa</button></div><div className="panel">{table(['Vencimento','Descrição','Valor',''],s.purchases.filter(p=>!p.paid).sort((a,b)=>String(a.due).localeCompare(String(b.due))).map(p=>{const v=situacaoVencimento(p.due,today());return [<span className="venc"><span className={v.tom==='atrasada'?'negative':''}>{dt(p.due)}</span>{v.texto&&<span className={'venc-tag '+v.tom}>{v.texto}</span>}</span>,p.description,brl(p.amount),<button className="btn small" disabled={busy} onClick={()=>{setForm({date:today()});setDialog({type:'payPurchase',id:p.id,title:'Registrar pagamento · '+p.description})}}>Registrar pagamento</button>]}))}</div></TabsContent><TabsContent value="history"><div className="panel">{table(['Data','Pedido','Forma','Valor',''],s.payments.filter(p=>p.date.startsWith(month)).slice().reverse().map(p=>[dt(p.date),'#'+s.orders.find(o=>o.id===p.orderId)?.number,p.method,brl(p.amount),<button className="text-btn" onClick={()=>printReceipt(p)}><Printer size={15}/> Gerar recibo</button>]))}</div></TabsContent></Tabs></>}
 {page==='Investimentos'&&<Investimentos s={s} ocupado={busy||!!error} salvar={mutate}/>}
 {page==='Configurações'&&<div className="settings-grid"><div className="panel"><div className="panel-heading"><h2>Dados da empresa</h2><button className="text-btn" onClick={editCompany}>Editar dados</button></div><div className="company-summary">{s.settings.logo?<img src={s.settings.logo} alt="Logo da empresa" className="company-logo-preview"/>:<div className="company-logo-empty"><Box size={25}/><span>Sem logo</span></div>}<div><h3>{s.settings.company||'Minha empresa'}</h3><p>{s.settings.document||'CPF/CNPJ não informado'}</p></div></div><dl className="settings-list company-details">{[['Telefone',s.settings.phone||'—'],['E-mail',s.settings.email||'—'],['Endereço',s.settings.address||'—']].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><p className="inline-note">Esses dados aparecem nos orçamentos e recibos impressos.</p></div><div className="panel"><div className="panel-heading"><h2>Custos padrão</h2><button className="text-btn" onClick={()=>{setForm({...s.settings});setDialog({type:'settings',title:'Parâmetros de custo'})}}>Editar</button></div><dl className="settings-list">{[['Energia',brl(s.settings.energyRate)+'/kWh'],['Hora de máquina padrão',brl(s.settings.machineRate)+'/h'],['Mão de obra padrão',brl(s.settings.laborRate)+'/h'],['Manutenção',s.settings.maintenance+'%'],['Pintura',brl(s.settings.paintRate)+'/100 g']].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><p className="inline-note">A impressora pode ter sua própria hora de máquina. Orçamentos salvos mantêm seus valores.</p></div><div className="panel settings-export"><div className="panel-heading"><h2>Backup dos seus dados</h2></div><p className="pad-copy">Exporte cadastros, orçamentos, pedidos e movimentações em um arquivo JSON. As fotos e a logo ficam salvas no sistema; o arquivo guarda apenas seus endereços.</p><button className="btn secondary" onClick={exportData}><Download size={17}/> Exportar dados</button></div></div>}
 </>}
 <footer className="workspace-footer"><span>GESTÃO 3D</span><span>Da primeira camada ao próximo pedido.</span></footer></main></SidebarInset>
 <Dialog open={!!dialog} onOpenChange={v=>{if(!v&&!busy)setDialog(null)}}><DialogContent className="app-dialog"><DialogHeader><DialogTitle>{dialog?.title}</DialogTitle><DialogDescription>{dialog?.type==='company'?'Esses dados aparecem nos orçamentos e recibos impressos.':dialog?.type==='quoteDetail'?'Valores e custos preservados no momento do orçamento.':'Preencha os dados e salve para atualizar sua operação.'}</DialogDescription></DialogHeader>{dialog&&<form onSubmit={dialog.type==='payPurchase'?async e=>{e.preventDefault();if(await mutate({type:'payPurchase',id:dialog.id,date:form.date}))setDialog(null)}:saveDialog}>
 {dialog.type==='entity'&&<>{dialog.kind==='suppliers'?<div className="fields"><Input label="Nome do fornecedor" required value={form.name} onChange={v=>patch('name',v)}/><Pick label="Tipo de fornecedor" value={form.supplierType||''} onChange={v=>patch('supplierType',v)} options={[{id:'online',name:'Online'},{id:'fisico',name:'Físico'}]}/>{form.supplierType==='online'&&<><Pick label="Plataforma" value={form.platform||''} onChange={v=>patch('platform',v)} options={['Mercado Livre','Shopee','Amazon','Outro site'].map(v=>({id:v,name:v}))}/><Input label="Link da loja ou do anúncio" type="url" value={form.link||''} onChange={v=>patch('link',v)} hint="Cole o endereço completo, começando com https://."/></>}{form.supplierType==='fisico'&&<><Input label="Telefone / WhatsApp" value={form.phone} onChange={v=>patch('phone',v)}/><Input label="Endereço da loja" value={form.address||''} onChange={v=>patch('address',v)}/></>}<Input label="Observações" value={form.notes} onChange={v=>patch('notes',v)}/></div>:<div className="fields">{entityFields[dialog.kind as Kind].map(([k,l,t])=>k==='installments'&&form.paymentType!=='parcelado'?null:t==='supplier'?<Pick key={k} label={l} value={form[k]||''} onChange={v=>patch(k,v)} options={s.suppliers}/>:['kgPrice','machineRate','spoolPrice'].includes(k)?<MoneyInput key={k} label={l} min={0} required={false} value={form[k]} onChange={v=>patch(k,v)}/>:<Input key={k} label={l} type={t} min={t==='number'?0:undefined} step={k==='spoolCount'?'1':undefined} hint={k==='spoolCount'?'No cadastro inicial, a quantidade entra no estoque automaticamente.':''} required={['name','type','color','category'].includes(k)} value={form[k]} onChange={v=>patch(k,v)}/>)}</div>}{dialog.kind==='products'&&<Field label="Foto do produto (até 5 MB)"><input type="file" accept="image/png,image/jpeg,image/webp" onChange={async e=>{const f=e.target.files?.[0];if(f){setBusy(true);try{patch('photo',(await upload(f)).url);toast.success('Foto enviada')}catch(x:any){toast.error(x.message)}finally{setBusy(false)}}}}/>{form.photo&&<img className="product-photo" src={form.photo} alt="Foto do produto"/>}</Field>}</>}
 {dialog.type==='production'&&<><div className="order-detail"><Badge>{form.stage}</Badge><span>Entrega {dt(form.due)}</span><b>{brl(form.revenue)}</b></div>{form.items?.map((i:any)=><div className="detail-item" key={i.id}><b>{i.calculation.quantity}× {i.name}</b><span>{s.printers.find(p=>p.id===i.printerId)?.name} · {i.calculation.hours} h/peça</span>{i.calculation.custom&&<small>Personalização: {i.calculation.customDescription||'Sem descrição'} · {i.calculation.customMinutes} min · {brl(i.calculation.customRate)}/h</small>}{i.arquivos?.length?<span className="anexos-linha">{i.arquivos.map((a:any)=><a key={a.url} href={a.url} target="_blank" rel="noopener noreferrer"><Paperclip size={14}/>{a.nome}</a>)}</span>:null}</div>)}<Pick label="Etapa atual" value={form.stage} onChange={v=>{if(v)patch('stage',v)}} options={stages.map(v=>({id:v,name:v}))}/><div className="checklist">{[['printed','Impressão concluída'],...(form.items?.some((i:any)=>i.calculation.paint)?[['painted','Pintura concluída']]:[]),['packed','Embalado'],['delivered','Entregue']].map(([k,l])=><label key={k}><Checkbox checked={form[k]} onCheckedChange={v=>{patch(k,!!v);if(k==='delivered'&&v)patch('stage','Entregue')}}/>{l}</label>)}</div><p className="inline-note">Pintura é exigida apenas quando prevista. Fotos são opcionais. A baixa usa o material previsto, incluindo a reserva; registre perdas extras ou diferenças em Ajustar estoque.</p><Field label="Fotos da produção (até 5 MB cada)"><input type="file" accept="image/png,image/jpeg,image/webp" disabled={busy} onChange={async e=>{const f=e.target.files?.[0];if(f){try{const key=(await upload(f)).url;if(await mutate({type:'photo',id:dialog.id,key}))patch('photos',[...form.photos,key])}catch(x:any){toast.error(x.message)}}}}/></Field><div className="photo-strip">{form.photos?.map((url:string)=><a href={url} target="_blank" rel="noreferrer" key={url}><img src={url} alt="Foto da produção"/></a>)}</div><div className="detail-item"><b>Recebido: {brl(received(s,form.id))}</b><span>Saldo: {brl(form.revenue-received(s,form.id))}</span></div>{form.notes&&<p>{form.notes}</p>}</>}
 {dialog.type==='payment'&&<div className="fields"><MoneyInput required label="Valor recebido (R$)" min={0.01} value={form.amount} onChange={v=>patch('amount',v)}/><Input required label="Data do recebimento" type="date" value={form.date} onChange={v=>patch('date',v)}/><Pick label="Forma de pagamento" value={form.method} onChange={v=>patch('method',v)} options={['Pix','Dinheiro','Cartão','Transferência','Outro'].map(v=>({id:v,name:v}))}/></div>}
 {dialog.type==='payPurchase'&&<Input label="Data do pagamento" required type="date" value={form.date} onChange={v=>patch('date',v)}/>}
 {dialog.type==='purchase'&&<><div className="fields"><Input required label="Descrição" value={form.description} onChange={v=>patch('description',v)}/><Pick label="Fornecedor (opcional)" value={form.supplierId} options={s.suppliers} onChange={v=>patch('supplierId',v)}/><Input label="Categoria" required value={form.category} onChange={v=>patch('category',v)}/><MoneyInput label="Valor total (R$)" required min={0.01} value={form.amount} onChange={v=>patch('amount',v)}/><Input label="Forma de pagamento" type="payment" value={form.paymentType} onChange={v=>patch('paymentType',v)}/>{form.paymentType==='parcelado'&&<Input label="Quantidade de parcelas" type="number" min={2} step="1" required value={form.installments} onChange={v=>patch('installments',v)}/>}<Input label="Data da compra" type="date" required value={form.date} onChange={v=>patch('date',v)}/><Input label="Vencimento" type="date" required value={form.due} onChange={v=>patch('due',v)}/><Pick label="Entrada no estoque (opcional)" value={form.materialId} options={s.materials} onChange={v=>patch('materialId',v)} hint="Selecione apenas se esta compra inclui filamento."/>{form.materialId&&<Input label="Quantidade recebida (g)" type="number" min={0.01} required value={form.grams} onChange={v=>patch('grams',v)}/>}</div><label className="check-row"><Checkbox checked={form.paid} onCheckedChange={v=>patch('paid',!!v)}/>Pago na data da compra</label></>}
 {dialog.type==='movement'&&<div className="fields"><Pick label="Material" value={form.materialId} options={s.materials} onChange={v=>patch('materialId',v)}/><Input label="Quantidade (g)" type="number" required value={form.grams} onChange={v=>patch('grams',v)} hint="Positivo para entrada; negativo para perdas ou saídas."/><Input label="Data" type="date" required value={form.date} onChange={v=>patch('date',v)}/><Input label="Motivo" required value={form.reason} onChange={v=>patch('reason',v)}/></div>}
 {dialog.type==='company'&&<><div className="fields"><Input required label="Nome da empresa / razão social" value={form.company} onChange={v=>patch('company',v)}/><Input label="CPF ou CNPJ" value={form.document} onChange={v=>patch('document',v)}/><Input label="Telefone / WhatsApp" value={form.phone} onChange={v=>patch('phone',v)}/><Input label="E-mail" type="email" value={form.email} onChange={v=>patch('email',v)}/><Input label="Endereço completo" value={form.address} onChange={v=>patch('address',v)}/></div><Field label="Logo da empresa (até 5 MB)" hint="PNG, JPG ou WebP. A logo aparece nos documentos impressos."><input type="file" accept="image/png,image/jpeg,image/webp" disabled={busy} onChange={async e=>{const f=e.target.files?.[0];if(f){setBusy(true);try{patch('logo',(await upload(f)).url);toast.success('Logo enviada')}catch(x:any){toast.error(x.message)}finally{setBusy(false)}}}}/></Field>{form.logo&&<div className="company-logo-row"><img className="company-logo-preview" src={form.logo} alt="Logo selecionada"/><button type="button" className="text-btn" onClick={()=>patch('logo','')}>Remover logo</button></div>}</>}
 {dialog.type==='settings'&&<div className="fields">{[['energyRate','Energia (R$/kWh)','number'],['machineRate','Hora de máquina padrão (R$/h)','number'],['laborRate','Mão de obra (R$/h)','number'],['maintenance','Manutenção (%)','number'],['paintRate','Pintura (R$/100 g)','number']].map(([k,l,t])=>['energyRate','machineRate','laborRate','paintRate'].includes(k)?<MoneyInput key={k} label={l} min={0} required value={form[k]} onChange={v=>patch(k,v)}/>:<Input key={k} label={l} type={t} min={0} required value={form[k]} onChange={v=>patch(k,v)}/>)}</div>}
 {dialog.type==='quoteDetail'&&<div className="quote-detail"><p><b>{form.customerName}</b> · Entrega {dt(form.due)}</p>{form.items.map((i:any)=><div className="detail-item" key={i.id}><b>{i.calculation.quantity}× {i.name} · {brl(i.revenue)}</b><span>Custo: {brl(i.cost)} · Máquina: {brl(i.calculation.machineRate)}/h</span>{i.calculation.custom&&<span>Personalização: {i.calculation.customDescription} · {i.calculation.customMinutes} min × {brl(i.calculation.customRate)}/h · {i.calculation.customScope==='peca'?'por peça':'por lote'}</span>}{i.arquivos?.length?<span className="anexos-linha">{i.arquivos.map((a:any)=><a key={a.url} href={a.url} target="_blank" rel="noopener noreferrer"><Paperclip size={14}/>{a.nome}</a>)}</span>:null}</div>)}<p>Custo total: <b>{brl(form.cost)}</b></p><p>Venda: <b>{brl(form.revenue)}</b></p><p>Resultado estimado: <b>{brl(form.revenue-form.cost)}</b></p><p>{form.notes}</p></div>}
 <div className="dialog-actions"><button type="button" className="btn secondary" onClick={()=>setDialog(null)} disabled={busy}>Fechar</button>{dialog.type!=='quoteDetail'&&<button type="submit" className="btn" disabled={busy}>{busy?'Salvando…':'Salvar'}</button>}</div></form>}</DialogContent></Dialog><Toaster richColors position="top-right"/></SidebarProvider>
}
